version: "3"

services:
  db:
    image: supabase/postgres:15.8.1.048
    ports:
      - "5433:5432"
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    environment:
      POSTGRES_PASSWORD: postgres
